
[dependencies]
  fastly = "^0.8.0"
  serde = { version = "^1", features = ["derive"] }

[package]
  edition = "2018"
  name = "fastly-fauna-gql"
  version = "0.1.0"

[profile]

  [profile.release]
    debug = 1
